function trainingStats = train_ppo_short()
setup_paths();
cfg = defaults();

% --- Short but meaningful training ---
cfg.maxEpisodes = 25;
cfg.T_end_train = 120;
cfg.maxStepsPerEpisode = floor(cfg.T_end_train / cfg.Ts);
cfg.trainCases = {'step_5','step_10','step_15','step_20','large_drop'};
assignin('base','T_end',cfg.T_end_train);
assignin('base','useRL',1);

env = make_env(cfg);
agentObj = make_agent_ppo(cfg, env);
assignin('base','agentObj',agentObj);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes = cfg.maxEpisodes, ...
    MaxStepsPerEpisode = cfg.maxStepsPerEpisode, ...
    ScoreAveragingWindowLength = 5, ...
    StopTrainingCriteria = "EpisodeCount", ...
    StopTrainingValue = cfg.maxEpisodes, ...
    SaveAgentCriteria = "EpisodeCount", ...
    SaveAgentValue = 5, ...
    SaveAgentDirectory = cfg.saveAgentDirectory, ...
    Verbose = true, ...
    Plots = "training-progress" ...
    );

trainingStats = train(agentObj, env, trainOpts);

stamp = datestr(now,'yyyymmdd_HHMMSS');
save(fullfile(cfg.saveAgentDirectory, "ppo_short_" + stamp + ".mat"), ...
    "agentObj", "cfg", "trainingStats");

fprintf('[train_ppo_short] Short training complete.\n');
end