function trainingStats = train_ppo()
setup_paths();
cfg = defaults();

env = make_env(cfg);
agentObj = make_agent_ppo(cfg, env);
assignin('base','agentObj',agentObj);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes = cfg.maxEpisodes, ...
    MaxStepsPerEpisode = cfg.maxStepsPerEpisode, ...
    ScoreAveragingWindowLength = cfg.scoreWindowLength, ...
    StopTrainingCriteria = "EpisodeCount", ...
    StopTrainingValue = cfg.maxEpisodes, ...
    SaveAgentCriteria = "EpisodeCount", ...
    SaveAgentValue = 25, ...
    SaveAgentDirectory = cfg.saveAgentDirectory, ...
    Verbose = true, ...
    Plots = "training-progress" ...
    );

trainingStats = train(agentObj, env, trainOpts);

stamp = datestr(now,'yyyymmdd_HHMMSS');
save(fullfile(cfg.saveAgentDirectory, "ppo_agent_" + stamp + ".mat"), ...
    "agentObj", "cfg", "trainingStats");
end