function trainingStats = train_ppo()
setup_paths();
cfg = defaults();

env = make_env(cfg);
agent = make_agent_ppo(cfg, env);

trainOpts = rlTrainingOptions( ...
    MaxEpisodes = cfg.maxEpisodes, ...
    MaxStepsPerEpisode = cfg.maxStepsPerEpisode, ...
    ScoreAveragingWindowLength = cfg.scoreWindowLength, ...
    StopTrainingCriteria = "AverageReward", ...
    StopTrainingValue = cfg.stopTrainingValue, ...
    SaveAgentCriteria = "EpisodeReward", ...
    SaveAgentValue = 200, ...
    SaveAgentDirectory = cfg.saveAgentDirectory, ...
    Verbose = true, ...
    Plots = "training-progress" ...
    );

trainingStats = train(agent, env, trainOpts);

stamp = datestr(now,'yyyymmdd_HHMMSS');
save(fullfile(cfg.saveAgentDirectory, "ppo_agent_" + stamp + ".mat"), ...
    "agent", "cfg", "trainingStats");
end